baseURL = "https://copybook.com/"
languageCode = "en-us"
title = "Copy Book"

enableRobotsTXT = true
enableEmoji = true
canonifyURLs = true
enableGitInfo = true

[params]
  description = ""

[author]
  name = "Praveen Juge"
  github = "praveenjuge"
  twitter = "praveenjuge"
  dribbble = "praveenjuge"
  behance = "praveenjuge"
