baseURL = "https://copybook.me/"
languageCode = "en-us"
title = "Copy Book"

enableRobotsTXT = true
enableEmoji = true

[taxonomies]
  tag = 'tags'
  mood = 'mood'
  category = 'categories'

[params]
  description = ""

[author]
  name = "Praveen Juge"
  github = "praveenjuge"
  twitter = "praveenjuge"
  dribbble = "praveenjuge"
  behance = "praveenjuge"
