baseURL = "https://copybook.netlify.app/"
languageCode = "en-us"
title = "Copy Book"

enableRobotsTXT = true
enableEmoji = true
canonifyURLs = true
enableGitInfo = true

[taxonomies]
  category = 'categories'
  tag = 'tags'
  mood = 'mood'

[params]
  description = ""

[author]
  name = "Praveen Juge"
  github = "praveenjuge"
  twitter = "praveenjuge"
  dribbble = "praveenjuge"
  behance = "praveenjuge"
