baseURL = "https://copybook.com/"
languageCode = "en-us"
title = "Copy Book"

enableRobotsTXT = true
enableEmoji = true
canonifyURLs = true

[params]
  description = "Praveen Juge is designing and making things for-and-in web, this is his personal website. And he likes speaking about himself in third person."

[author]
  name = "Praveen Juge"
  github = "praveenjuge"
  twitter = "praveenjuge"
  dribbble = "praveenjuge"
  behance = "praveenjuge"
