backend:
  name: git-gateway
  branch: main
media_folder: static/images
public_folder: /images
site_url: "https://copybook.netlify.app/"
display_url: "https://copybook.netlify.app/"
logo_url: https://copybook.netlify.app/images/logo.svg
collections:
  - name: "Content"
    identifier_field: body
    label: "Content"
    folder: "content"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - name: "mood"
        label: "Mood"
        widget: "create-select"
        mode: "xml"
        url: "https://copybook.netlify.app/mood/index.xml"
        query: "item > title"
        multiple: false
        required: true
      - name: "categories"
        label: "Categories"
        widget: "create-select"
        mode: "xml"
        url: "https://copybook.netlify.app/categories/index.xml"
        query: "item > title"
        multiple: false
        required: true
      - name: "tags"
        label: "Tags"
        widget: "create-select"
        mode: "xml"
        url: "https://copybook.netlify.app/tags/index.xml"
        query: "item > title"
        multiple: true
        required: true
      - { label: "Body", name: "body", widget: "markdown", required: true }
